image:
  repository: lmscommunity/logitechmediaserver
  pullPolicy: IfNotPresent
  tag: "v8.4.0"

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

environment:
  timezone: "America/Denver"

service:
  type: "LoadBalancer"
  loadBalancerIP: ""
  ports:
    webapi: 9000

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
    # - host: lms.speedport.ip
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - lms.speedport.ip

persistence:
  enabled: true
  accessMode: ReadWriteOnce 
  size: 1Gi 
  storageClass: local-path-retain
  annotations: {}

podSecurityContext: {}
  # runAsUser: 999
  # fsGroup: 999

securityContext: {}
#  capabilities:
#     drop:
#     - ALL
#  readOnlyRootFilesystem: false
#  runAsNonRoot: true
#  runAsUser: 999

resources: 
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi


nodeSelector: {}

tolerations: []

affinity: {}
