services:
  lms:
    container_name: lms
    image: lmscommunity/logitechmediaserver:9.0.0
    pull_policy: always
    # Necessary for squeeze2upnp, Spotify Connect (using Avahi)
    network_mode: "host"
    volumes:
      - ~/.docker/lms/config:/config:rw
      - ${MUSIC_DIR}:/music:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.05.2
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8888:80/tcp
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      - '~/.docker/pihole/etc:/etc/pihole'
      - '~/.docker/pihole/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
