apiVersion: v2
name: unifi-controller
description: A Helm chart for deploying a unifi-controller on Kubernetes
type: application
version: 1.1.0
keywords:
  - unifi
  - controller 
  - ubiquiti
home: https://github.com/sarumont/homelab/charts/unifi-controller
appVersion: "v6.5.55"
maintainers:
  - name: Richard Kolkovich
    email: richard@sigil.org
    url: https://sigil.org
# annotations:
#   example: A list of annotations keyed by name (optional).
