#cloud-config
runcmd:
  - apt install dkms build-* linux-headers-$(uname -r) linux-modules-extra-$(uname -r) -y
  - wget https://github.com/strongtz/i915-sriov-dkms/releases/download/2025.02.03/i915-sriov-dkms_2025.02.03_amd64.deb
  - apt install ./i915-sriov-dkms_2025.02.03_amd64.deb -y
  - echo "blacklist xe" > /etc/modprobe.d/blacklist.conf
  - echo "options i915 enable_guc=3" > /etc/modprobe.d/i915.conf
  - update-grub

power_state:
  delay: now
  mode: reboot
  message: "Reboot after installing DKMS module"
  condition: true
